# Generated by Django 5.1.2 on 2024-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3'), ('Category 4', 'Category 4'), ('Category 5', 'Category 5')], max_length=20)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('assigned_to', models.CharField(max_length=100)),
            ],
        ),
    ]
