# Generated by Django 5.1.2 on 2024-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
