# Generated by Django 5.1.1 on 2024-11-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('green', 'Completed'), ('yellow', 'Ongoing'), ('red', 'Todo')], max_length=10),
        ),
    ]
