# Generated by Django 5.1.1 on 2024-11-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_chat_message_cchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='cchat',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Messages.chat'),
            preserve_default=False,
        ),
    ]
