# Generated by Django 5.1.1 on 2024-11-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_users_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
