# Generated by Django 5.1.1 on 2024-11-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_team_team_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pics/'),
        ),
    ]
